{
   "tran_id":[
      "45c60e2c-e64a-42f8-832a-ab696ac05851"
   ],
   "val_id":[
      "260519181430oG2w3vvLOUGrHlu"
   ],
   "amount":[
      "400.00"
   ],
   "card_type":[
      "BKASH-BKash"
   ],
   "store_amount":[
      "390.00"
   ],
   "card_no":[
      ""
   ],
   "bank_tran_id":[
      "260519181430UjyA88wjV70YKYv"
   ],
   "status":[
      "VALID"
   ],
   "tran_date":[
      "2026-05-19 18:14:22"
   ],
   "error":[
      ""
   ],
   "currency":[
      "BDT"
   ],
   "card_issuer":[
      "BKash Mobile Banking"
   ],
   "card_brand":[
      "MOBILEBANKING"
   ],
   "card_sub_brand":[
      "Classic"
   ],
   "card_issuer_country":[
      "Bangladesh"
   ],
   "card_issuer_country_code":[
      "BD"
   ],
   "store_id":[
      "argho6a05c23a410ee"
   ],
   "verify_sign":[
      "3c5d25a1444588f9e28fc6734c79b629"
   ],
   "verify_key":[
      "amount,bank_tran_id,base_fair,card_brand,card_issuer,card_issuer_country,card_issuer_country_code,card_no,card_sub_brand,card_type,currency,currency_amount,currency_rate,currency_type,error,risk_level,risk_title,status,store_amount,store_id,tran_date,tran_id,val_id,value_a,value_b,value_c,value_d"
   ],
   "verify_sign_sha2":[
      "d01d44f69dda3a881142a7c0567df416b2dd93fb34cea5bdd6e4d516643b1558"
   ],
   "currency_type":[
      "BDT"
   ],
   "currency_amount":[
      "400.00"
   ],
   "currency_rate":[
      "1.0000"
   ],
   "base_fair":[
      "0.00"
   ],
   "value_a":[
      ""
   ],
   "value_b":[
      ""
   ],
   "value_c":[
      ""
   ],
   "value_d":[
      ""
   ],
   "subscription_id":[
      ""
   ],
   "risk_level":[
      "0"
   ],
   "risk_title":[
      "Safe"
   ]
}