{test
   "status":"SUCCESS",
   "failedreason":"",
   "sessionkey":"85CD52BEE0ABC9C8E8B4D84D545C1896",
   "gw":{
      "visa":"city_visa,ebl_visa,visacard",
      "master":"city_master,ebl_master,mastercard",
      "amex":"city_amex,amexcard",
      "othercards":"qcash,fastcash",
      "internetbanking":"city,abbank,bankasia,ibbl,mtbl,tapnpay,eblsky,instapay,pmoney,woori,modhumoti,fsibl",
      "mobilebanking":"dbblmobilebanking,bkash,nagad,abbank,ibbl,tap,upay,okaywallet,cellfine,mcash"
   },
   "redirectGatewayURL":"https://sandbox.sslcommerz.com/gwprocess/v4/bankgw/indexhtmlOTP.php?mamount=50.00&ssl_id=260519200828IAM5x4jk5feEX2h&Q=REDIRECT&SESSIONKEY=85CD52BEE0ABC9C8E8B4D84D545C1896&tran_type=success&cardname=",
   "directPaymentURLBank":"",
   "directPaymentURLCard":"",
   "directPaymentURL":"",
   "redirectGatewayURLFailed":"",
   "GatewayPageURL":"https://sandbox.sslcommerz.com/EasyCheckOut/testcde85cd52bee0abc9c8e8b4d84d545c1896",
   "storeBanner":"https://sandbox.sslcommerz.com/stores/logos/demoLogo.png",
   "storeLogo":"https://sandbox.sslcommerz.com/stores/logos/demoLogo.png",
   "store_name":"Demo",
   "desc":[
      {
         "name":"AMEX",
         "type":"amex",
         "logo":"https://sandbox.sslcommerz.com/gwprocess/v4/image/gw/amex.png",
         "gw":"amexcard",
         "r_flag":"1",
         "redirectGatewayURL":"https://sandbox.sslcommerz.com/gwprocess/v4/bankgw/indexhtmlOTP.php?mamount=50.00&ssl_id=260519200828IAM5x4jk5feEX2h&Q=REDIRECT&SESSIONKEY=85CD52BEE0ABC9C8E8B4D84D545C1896&tran_type=success&cardname=amexcard"
      }, 
   ],
   "is_direct_pay_enable":"0"
}




{
   "tran_id":[
      "45c60e2c-e64a-42f8-832a-ab696ac05851"
   ],
   "val_id":[
      "260519181430oG2w3vvLOUGrHlu"
   ],
   "amount":[
      "400.00"
   ],
   "card_type":[
      "BKASH-BKash"
   ],
   "store_amount":[
      "390.00"
   ],
   "bank_tran_id":[
      "260519181430UjyA88wjV70YKYv"
   ],
   "status":[
      "VALID"
   ],
   "tran_date":[
      "2026-05-19 18:14:22"
   ],
   "error":[
      ""
   ],
   "currency":[
      "BDT"
   ],
   "card_issuer":[
      "BKash Mobile Banking"
   ],
   "card_brand":[
      "MOBILEBANKING"
   ],
   "card_sub_brand":[
      "Classic"
   ],
   "card_issuer_country":[
      "Bangladesh"
   ],
   "card_issuer_country_code":[
      "BD"
   ],
   "store_id":[
      "argho6a05c23a410ee"
   ],
   "verify_sign":[
      "3c5d25a1444588f9e28fc6734c79b629"
   ],
   "verify_key":[
      "amount,bank_tran_id,base_fair,card_brand,card_issuer,card_issuer_country,card_issuer_country_code,card_no,card_sub_brand,card_type,currency,currency_amount,currency_rate,currency_type,error,risk_level,risk_title,status,store_amount,store_id,tran_date,tran_id,val_id,value_a,value_b,value_c,value_d"
   ],
   "verify_sign_sha2":[
      "d01d44f69dda3a881142a7c0567df416b2dd93fb34cea5bdd6e4d516643b1558"
   ],
   "risk_level":[
      "0"
   ],
   "risk_title":[
      "Safe"
   ]
}