# Generated by Django 6.0.5 on 2026-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0012_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Success', 'Successful'), ('Fail', 'Failed'), ('Cancel', 'Cancel'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
    ]
