# Generated by Django 6.0.5 on 2026-05-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0013_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
