# Generated by Django 6.0.5 on 2026-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0016_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=50, null=True),
        ),
    ]
