# Generated by Django 6.0.5 on 2026-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0017_alter_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('Success', 'Successful'), ('Fail', 'Failed'), ('Cancel', 'Cancel'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, null=True),
        ),
    ]
