# Generated by Django 6.0.5 on 2026-05-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0019_alter_order_error_alter_order_store_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stacard_issuertus',
            new_name='card_issuer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_fair',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='value_a',
        ),
        migrations.RemoveField(
            model_name='order',
            name='value_b',
        ),
        migrations.RemoveField(
            model_name='order',
            name='value_c',
        ),
        migrations.RemoveField(
            model_name='order',
            name='value_d',
        ),
    ]
