# Generated by Django 6.0.5 on 2026-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0020_rename_stacard_issuertus_order_card_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
