# Generated by Django 6.0.5 on 2026-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0021_custom_user_address_custom_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='city',
            field=models.CharField(blank=True, default='Khulna_default', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='risk_level',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='risk_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
