# Generated by Django 6.0.5 on 2026-05-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0022_alter_custom_user_address_alter_custom_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='connection_state',
        ),
    ]
