# Generated by Django 6.0.5 on 2026-05-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0023_rename_state_order_connection_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sessionkey',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
