# Generated by Django 6.0.5 on 2026-05-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0024_order_sessionkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sessionkey',
            new_name='session_key',
        ),
    ]
