# Generated by Django 6.0.5 on 2026-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0025_rename_sessionkey_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
