# Generated by Django 6.0.5 on 2026-05-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0026_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='connection_state',
            new_name='connection_status',
        ),
    ]
