# Generated by Django 6.0.5 on 2026-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0027_rename_connection_state_order_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='connection_status',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
    ]
