# Generated by Django 6.0.5 on 2026-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0028_alter_order_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
