# Generated by Django 6.0.5 on 2026-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0029_alter_custom_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.IntegerField(blank=True, default='+8801712345678', null=True),
        ),
    ]
