# Generated by Django 6.0.5 on 2026-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0030_alter_custom_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.IntegerField(blank=True, default='123456789', null=True),
        ),
    ]
